- id: doi:10.1101/2024.10.10.617585
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/Fig-Bat-paper.png

- id: doi:10.1038/s41467-024-47658-x
  type: paper
  image: images/nature-communications-logo.png
  
- id: doi:10.1242/dev.201562
  type: paper
  image: images/Fig-Sall1-paper.png

- id: doi:10.1002/jez.b.23142
  type: paper
  image: images/Fig-CellAdhesion-paper.png

- id: doi:10.1101/2023.03.22.533123
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/BioRxiv_logo.png

- id: doi:10.1101/2022.10.28.514220
  type: paper
  description: Currently as a preprint on BioRxiv.
  image: images/BioRxiv_logo.png

- id: doi:10.1038/s41588-022-01117-9
  type: paper
  image: images/naturegenetics-logo.png

- id: doi:10.1101/2022.01.12.476048
  type: paper
  description: BioRxiv published later as.
  image: images/BioRxiv_logo.png

- id: doi:10.1101/2021.04.14.439779
  type: paper
  description: BioRxiv published later as.
  image: images/BioRxiv_logo.png

- id: doi:10.3390/ani11061639
  type: paper
  image: images/animals-logo.png

- id: doi:10.1126/science.aaz2582
  type: paper
  image: images/Fig-Science-paper.png

- id: doi:10.1093/molehr/gaaa027
  type: paper
  image: images/molehr_logo.png

- id: doi:10.1371/journal.pone.0197685
  type: paper
  image: images/plosone-logo.png

- id: doi:10.7554/eLife.15635
  type: paper
  image: images/elife-logo.png

- id: doi:10.1095/biolreprod.113.110957
  type: paper
  image: images/boreproduction-logo.png

- id: doi:10.1095/biolreprod.112.106708
  type: paper
  image: images/boreproduction-logo.png

- id: doi:10.1002/jez.b.22000
  type: paper
  image: images/jezb-logo.png
  authors:
  - "Dar\xEDo G. Lupi\xE1\xF1ez"
  - Francisca M. Real
  - Rajesh K. Dadhich
  - Francisco D. Carmona
  - Miguel Burgos
  - Francisco J. Barrionuevo
  - "Rafael Jim\xE9nez"

- id: doi:10.1159/000323805
  type: paper
  image: images/sxd-logo.png

- id: doi:10.1095/biolreprod.109.080135
  type: paper
  image: images/boreproduction-logo.png

- id: doi:10.1002/jez.b.21291
  type: paper
  image: images/jezb-logo.png

